### ISSUE TITLE
Guntime Branch: Bullet Accuracy Issue

### ISSUE THREAD

**Issue by Ch-i-ef** [rafaVls/untitled-shooter#5]
Bullet accuracy wack again, might try redoing the **Shooting** and **Bullet** scripts

 _(unless a certain someone wants to dive into shit to try and fix it themself)_

**Comment by rafaVls** [comment]
are you asking me to fix it or are you throwing shade at me for messing with your code?

**Comment by rafaVls** [comment]
also, I appreciate that you opened up an issue for this 🤙🏽

**Comment by Ch-i-ef** [comment]
Both ( ͡° ͜ʖ ͡°)
